NUM_EPOCHS = 1
LEARNING_RATE = 1e-4
BATCH_SIZE = 4
WEIGHT_DECAY = 1e-5
CLIP_GRAD_NORM = 1.0
LAMBDA_ROT = 1
LAMBDA_TRANS = 0
LAMBDA_LAV_CONST = 0.2
ACCUMULATION_STEPS = 1
LAMBDA_l2_PC = 0.1

NUM_POINTS = 1024
NUM_PARTS = 7
NUM_FRAMES = 35

EXPERIMENT_NAME = f"DYNAMO_checkpoint"
CHECKPOINT_DIR = "checkpoints"
CHECKPOINT_PATH = f"{CHECKPOINT_DIR}/{EXPERIMENT_NAME}_best.pt"

DATA_BASE_PATH = "data/processed"
TRAIN_LIST_PATH = f"{DATA_BASE_PATH}/train_list.txt"
TEST_LIST_PATH = f"{DATA_BASE_PATH}/test_list.txt"